### ISSUE TITLE
Can't run locally

### ISSUE THREAD

**Issue by RovaHerve** [abbas99-hub/Job-Recommendation-System#1]
Hello abbas99-hub,
Can you fix this issue, I can't run the app in my local computer. 
I have this error . 
![image](https://github.com/user-attachments/assets/cffdbc25-f88d-493e-a06a-30f0d40579cd)

2024-12-14 21:09:53.198 Uncaught app execution
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File "C:\Users\Admin\volamena\ketrika\Job-Recommendation-System\__init__.py", line 6, in <module>
    from src.components.job_recommender import ngrams,getNearestN,jd_df
  File "C:\Users\Admin\volamena\ketrika\Job-Recommendation-System\src\components\job_recommender.py", line 14, in <module>
    import src.notebook.skills_extraction as skills_extraction
  File "C:\Users\Admin\volamena\ketrika\Job-Recommendation-System\src\notebook\skills_extraction.py", line 7, in <module>
    nlp = spacy.load('en_core_web_sm')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\spacy\__init__.py", line 51, in load
    return util.load_model(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\spacy\util.py", line 472, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.

**Comment by RovaHerve** [comment]
Issue resolved by making this two commands : 
python -m spacy download en_core_web_lg
python -m spacy download en_core_web_sm
